### ISSUE TITLE
TypeError: MetaApi is not a constructor

### ISSUE THREAD

**Issue by krButani** [agiliumtrade-ai/metaapi-node.js-sdk#16] opened 2022-07-12 06:57 UTC
const api = new MetaApi(token);
            ^

TypeError: MetaApi is not a constructor
    at file:///C:/Users/foxy/Desktop/express/meta/index.js:4:13
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)

**Comment by RomanKisilenko** [comment] 2022-07-12 07:06
Hello, I suspect your MetaApi import is not correct as we can not reproduce it on our side.

**Comment by RomanKisilenko** [comment] 2022-07-16 16:21
Closing this bugreport due to lack of details and response. Feel free to reopen it if you still think there is an issue in SDK.

**Closed by RomanKisilenko** 2022-07-16 16:21 UTC

**Comment by enzoferey** [comment] 2023-07-23 13:34
Hey @RomanKisilenko, just for you to know =>

I'm using:

```
"typescript": "^5.1.3"
"metaapi.cloud-sdk": "^23.4.1"
```

If you import the SDK as the README says:

```
import MetaApi from "metaapi.cloud-sdk";
```

You will need to invoke the constructor like this:

```
const api = new MetaApi.default(token);
```
